# Generated by Django 5.2.10 on 2026-02-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
